version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
    - '9090:80'
    volumes:
    - ${DB_DIR}:/usr/local/apache2/htdocs
    - ./httpd.conf:/usr/local/apache2/conf/httpd.conf